language: python
python:
  - "2.7"
  - "3.5"
install:
  - sudo apt-get install pylint
  - pip install pep8
  - pip install -r requirements.txt
script:
  - nosetests
  - pylint --errors-only hubsync
  - pep8 --max-line-length=90
